### ISSUE TITLE
Update on other pages.. 

### ISSUE THREAD

**Issue by WealthCity** [takismercouris/yahoo_finance#1]
Hello takis.mercouris..

Contacting as couldnt find ur mail id..

Nice to see your work.. and came to know online that u have been in the industry for more than 20 yrs.. its good that people of ur caliber are into open source development..

Ok like the repo ur working.. we had also worked on taking yahoo fundamental data by page scraping.. we could do it in slightly different way correctly.. even though we get into error occasional..

Saw ur comment that, "as u get time u will update ur repo".. that pushed me to give what we did out , so that it can help u and also others in developing the gem..

Looking forward for ur update... 

https://github.com/ajmal017/yahoo_fundamental

**Comment by takismercouris** [comment]
I just came about to look at your repository to see whether I could pick any of your work, but the link does not work anymore. If you are still interested, please update. Alternatively, let me know what pages you were looking to scrape.

thanks for your comment.
